In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("job.csv")

In [2]:
df.head(20)

    Years  result
0      22       0
1      25       0
2      47       1
3      52       0
4      46       1
5      56       1
6      55       0
7      60       1
8      62       1
9      61       1
10     18       0
11     28       0
12     27       0
13     29       0
14     49       1
15     55       1
16     25       1
17     58       1
18     19       0
19     18       0

In [3]:
df.tail()

    Years  result
22     40       1
23     45       1
24     50       1
25     54       1
26     23       0

In [4]:
# Splitting of the independent and dependent data variable(features) - 
x = df[['Years']]
y = df['result']

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,train_size=0.8,random_state=1)

In [6]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()