In [2]:
# Pandas - used to handle the data
# Pandas used to create the data frames and series 
# To simply install pandas library in local system use command pip install pandas
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series(data=[10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In Pandas the data created in two forms -
1. Series - It is one simple column of the table 
2. Dataframe - widely used method

In [4]:
s2 = pd.Series(data=[100,200,300,400,500])
s2

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [6]:
s3 = pd.Series(data=[1000,2000,3000,4000,5000],index = list('vwxyz'))
s3

v    1000
w    2000
x    3000
y    4000
z    5000
dtype: int64

In [ ]:
# Creating DataFrame - A table like structure which has rows and columns like CSV(Comma Separated Values)
df = pd.DataFrame({'C1':s1,'C2':s2})
df

   C1   C2
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500

In [ ]:
df = pd.DataFrame(data=np.random.randint(1,100,size=(1000,5)),columns=list("abcde"))
df

      a   b   c   d   e
0    47  53   2  67  22
1    35  73   9   3   7
2    60  33  13  71   6
3    66   1  11  19  23
4    88  90  52  31  49
..   ..  ..  ..  ..  ..
995  16  38  69  45  20
996  78  73   5  37  45
997  10  53  27  98  61
998  77  94  47  18  36
999  54  64  57  81  49

[1000 rows x 5 columns]